version: 0.0
os: linux
files:
  - source: target/listacomprathymeleaf-0.0.1-SNAPSHOT.jar
    destination: /usr/local/app
hooks:
  ApplicationStop:
    - location: aws/scripts/application-stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: aws/scripts/validate-service.sh
      timeout: 300
      runas: root
