name: Deployment
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: maven
          distribution: 'oracle'
      - name: Build with Maven
        run: mvn package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pacote
          path: |
            target/listacomprathymeleaf-0.0.1-SNAPSHOT.jar
            appspec.yml
            aws/**
      - name: Output contents
        run: ls
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Output contents
        run: ls
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: pacote
          path: .
      - name: Output contents
        run: ls
      - name: Output contents
        run: ls target
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: List Buckets
        run: aws s3 ls
      - name: Copy file
        run: aws s3 cp *.* s3://listacomprathymeleaf/
