name: Deployment
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: maven
          distribution: 'oracle'
      - name: Build with Maven
        run: mvn package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pacote
          path: target/listacomprathymeleaf-0.0.1-SNAPSHOT.jar
      - name: Copy artifacts to EC2 instance
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: target/listacomprathymeleaf-0.0.1-SNAPSHOT.jar
            target: /home/ec2-user
